### ISSUE TITLE
Custom aerial screensaver not downloaded

### ISSUE THREAD

**Issue by narut88** [FalconLee1011/Customized-Aerial-Screen-Saver#4]
When a new aerial screensaver is added from the app it appear in the screensavers list but it seems that the screensaver was not downloaded. When the Download button is clicked nothing happen. 

https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/assets/7955695/45eb254a-10e2-47b5-bf3b-0b499a87bd35

**Comment by FalconLee1011** [comment]
@narut88 Hi! with this utility, there's no need to click the download button in order to use the video you've imported.

If the download button appears, it might be some issue related to the video itself, try delete it and re-add it.

Here is the recommended video format
| Attribute | Requirements |
|:-|:-| 
| Length | At least 15 seconds |
| Audio Track | Prefer no audio track |
| FPS (Frames Per Second) | At 60 FPS |
| Aspect Ratio | 16:9 |
| Resolution | At least 1920x1080 |
| Video Format | Must be .mov |

If this issue still exists, feel free to drop more information for me to resolve it :)

**Comment by FalconLee1011** [comment]
Fixed in [version 1.1](https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/commit/962b2bd481c2c9737451c555d3c4b7b4a8083cb4)
